TYPES = {
    "walmart": "Retail store",
    "spotxchange": "Video advertising platform",
    "flashtalking": "User tracking and data collection with cookieless technologies.",
    "protected-media": "Bot and web sraping protection for advertising",
    "neustar": "Online marketing services",
    "huffingtonpost": "News aggregation service",
    "justpremium": "Multimedia reach web advertising service", 
    "piano-media": "Cross platform user tracking and profiling and users brands relationship builder",
    "hotjar": "Tracking users behavior on the visited sites, i.e., heatmaps and recording services",
    "clickagy": "Users intent generation streaming data",
    "paperg": "Ad impressions and user tracking monitoring tools",
    "drift": "Conversation bot for marketing purposes",
    "triple-lift": "Video advertising platform",
    "sharethrough": "RTB programmatic advertising",
    "taboola": "Web advertising platform",
    "skimlinks": "Content monetization through affiliate links",
    "connexity": "e-commerce advertising solution",
    "sublime-skinz": "Video advertising platform",
    "aol": "A company with multiple advertising roles",
    "inskin-media": "Multimedia-rich advertising platform",
    "district-m": "SSP RTB platform",
    "magnite": "Open Source Header Bidding Solutions",
    "tru-optik-data-corp": "provides real-time Market Intelligence SaaS for the Media, Entertainment & Advertising Industry",
    "yahoo": "A company with multiple advertising roles",
    "monetizer101": "smart affiliate marketing solutions",
    "smart-adserver": "A company with multiple advertising roles",
    "content-square": "Observe hidden customer behaviors, and use those insights to drive more successful experiences",
    "at-internet": "Measuring websites traffic - Analytics",
    "springserve": "Video advertising platform",
    "azerion": "Web advertising and monetization platform",
    "zoominfo": "Marketing data management platform",
    "gumgum": "Analyze digital media to allow content classification",
    "signal": "Web tracking and users segmentation",
    "doubleverify": "A company with multiple advertising roles",
    "dynadmic": "Video advertising platform",
    "sovrn": "A company with multiple advertising roles",
    "meetrics": "Monitoring tool to estimate ad campaigns performance",
    "yimg.com": "User tracking service",
    "skimresources.com": "Content monetization through affiliate links",
    "profitshare.ro": "Content monetization through affiliate links",
    "ad-score.com": "Bot and web scraping protection for advertising",
    "yahoo.com": "A company with multiple advertising roles",
    "yahoo.net": "A company with multiple advertising roles",
    "yimg.com": "User tracking service",
    "yimg.jp": "User tracking service",
    "atwola.com": "User tracking service",
    "blogsmithmedia.com": "User tracking service",
    "yahoo.co.jp": "A company with multiple advertising roles",
    "mxcdn.net": "Monitoring tool to estimate ad campaigns performance",
    "doubleverify.com": "A company with multiple advertising roles",
    "huffpost.com": "News aggregation service",
    "dailymotion.com": "News aggregation service",
    "dailymotionbus.com": "News aggregation service",
    "dmcdn.net": "News aggregation service",
    "meetrics.net": "Monitoring tool to estimate ad campaigns performance",
    "adtechus.com": "Advertising - Supply side platform",
    "gumgum.com": "Analyze digital media to allow content classification",
    "adtechjp.com": "A company with multiple advertising roles",
    "inskinad.com": "Multimedia-rich advertising platform",
    "truoptik.com": "Provides real-time Market Intelligence SaaS for the Media, Entertainment & Advertising Industry",
    "sascdn.com": "Brands protection services",
    "rtk.io": "Open Source Header Bidding Solutions",
    "btstatic.com": "Monitoring tool to estimate ad campaigns performance",
    "pictela.net": "Monitoring tool to estimate ad campaigns performance",
    "home.neustar": "User tracking service",
    "3lift.com": "Video advertising platform",
    "agkn.com": "A company with multiple advertising roles",
    "cxt.ms": "e-commerce advertising solution",
    "aliexpress.com": "e-commerce advertising solution",
    "connexity.net": "e-commerce advertising solution",
    "dyntrk.com": "Video advertising platform",
    "walmart.com": "Retail store",
    "districtm.ca": "SSP RTB platform",
    "springserve.com": "Video advertising platform",
    "spotxcdn.com": "Video advertising platform",
    "lijit.com": "A company with multiple advertising roles",
    "yahooapis.com": "Advertising APIs and tools",
    "driftt.com": "Conversation bot for marketing purposes",
    "360yield.com": "User tracking service",
    "tinypass.com": "Advertising cloud hosting service",
    "clickagy.com": "Users intent generation streaming data",
    "spotxchange.com": "Video advertising platform",
    "drift.com": "Conversation bot for marketing purposes",
    "huffingtonpost.com": "News aggregation service",
    "justpremium.com": "Video advertising platform",
    "zoominfo.com": "Marketing data management platform",
    "placelocal.com": "Ad impressions and user tracking monitoring tools",
    "ayads.co": "Video advertising platform",
    "districtm.io": "SSP RTB platform",
    "thebrighttag.com": "User tracking service",
    "monetizer101.com": "smart affiliate marketing solutions",
    "hotjar.com": "Tracking users behavior on the visited sites, i.e., heatmaps and recording services",
    "aol.com": "A company with multiple advertising roles",
    "xiti.com": "Measuring websites traffic - Analytics",
    "aolcdn.com": "A company with multiple advertising roles",
    "flashtalking.com": "User tracking and data collection with cookieless technologies.",
    "sharethrough.com": "RTB programmatic advertising",
    "taboola.com": "Web advertising platform",
    "contentsquare.net": "Observe hidden customer behaviors, and use those insights to drive more successful experiences",
    "oath.com": "A company with multiple advertising roles",
    "advertising.com": "A company with multiple advertising roles",
    "smartadserver.com": "A company with multiple advertising roles",
    "userapi.com": "User tracking service",
    "hubspot.com": "Customer Relationship Management - CRM Platform",
    "hs-sites.com": "Customer Relationship Management - CRM Platform",
    "hubspot.net": "Customer Relationship Management - CRM Platform",
    "hsstatic.net": "Customer Relationship Management - CRM Platform",
    "profitsmart.ro" : "Affiliate advertising",
    "media-amazon.com": "A company with multiple advertising roles",
    "adgrx.com": "TV Advertising",
    "android.com": "Mobile phone OS",
    "googledrive.com": "Cloud storage service",
    "evidon.com": "User tracking service",
    "hsappstatic.net": "Customer Relationship Management - CRM Platform",
    "azure.net": "Cloud services",
    "zanox.com": "Affiliate advertising",
    "alipay.com": "Payment system",
    "payments-amazon.com": "Payment system",
    "amazonpay.com": "Payment system",
    "stripe.com": "Payment system",
    "blogspot.in": "Blogging service",
    "google.co.ke": "A company with multiple advertising roles",
    "switchads.com": "Web advertising platform",
    "sitescout.com": "Web advertising platform",
    "youtube-nocookie.com": "A company with multiple advertising roles",
    "visualdna.com": "User tracking service",
    "office.net": "Cloud services",
    "adnxs.com": "A company with multiple advertising roles",
    "adform.net": "Web advertising platform",
    "bahn.de": "public transport services",
    "adobedtm.com": "User tracking service",
    "mercadolibre.com.co": "e-commerce advertising solution",
    "mercadolibre.cl": "e-commerce advertising solution",
    "mercadolibre.com.ve": "e-commerce advertising solution",
    "mercadolibre.com": "e-commerce advertising solution",
    "mercadolibre.com.mx": "e-commerce advertising solution",
    "mercadolibre.com.ar": "e-commerce advertising solution",
    "googlevideo.com": "A company with multiple advertising roles",
    "embedly.com": "Multimedia-rich advertising platform",
    "donkeymails.com": "email advertising",
    "dmxleo.com": "Unknown Service",
    "linksynergy.com": "Web advertising platform",
    "amazon.co.jp": "A company with multiple advertising roles",
    "googletagservices.com": "A company with multiple advertising roles",
    "pubmine.com": "Web advertising platform",
    "dm-event.net": "Brands protection services",
    "google.com.bo": "A company with multiple advertising roles",
    "amazon.fr": "A company with multiple advertising roles",
    "cedexis-radar.net": "User tracking service",
    "blogspot.ru": "Blogging service",
    "blogspot.com.co": "Blogging service",
    "blogspot.com.eg": "Blogging service",
    "widget-content.com": "Blogging service",
    "blogspot.md": "Blogging service",
    "blogspot.ro": "Blogging service",
    "blogspot.it": "Blogging service",
    "blogspot.cl": "Blogging service",
    "blogspot.co.uk": "Blogging service",
    "blogspot.de": "Blogging service",
    "blogspot.com.es": "Blogging service",
    "blogspot.mk": "Blogging service",
    "blogspot.dk": "Blogging service",
    "blogspot.com.br": "Blogging service",
    "blogspot.com.tr": "Blogging service",
    "blogspot.com": "Blogging service",
    "blogger.com": "Blogging service",
    "blogblog.com": "Blogging service",
    "btrll.com": "User tracking service",
    "adrcdn.com": "Web advertising platform",
    "jwplayer.com": "Video advertising platform",
    "jwplatform.com": "Video advertising platform",
    "avid-adserver.com": "Video advertising platform",
    "jwpcdn.com": "Video advertising platform",
    "jwpsrv.com": "Video advertising platform",
    "google.ee": "A company with multiple advertising roles",
    "gexperiments1.com": "A company with multiple advertising roles",
    "gexperiments2.com": "A company with multiple advertising roles",
    "gexperiments3.com": "A company with multiple advertising roles",
    "gexperiments4.com": "A company with multiple advertising roles",
    "live.com": "A company with multiple advertising roles",
    "dotomi.com": "User tracking service",
    "msn.com": "A company with multiple advertising roles",
    "nexage.com": "Mobile advertising",
    "ero-advertising.com": "Adult advertising",
    "adxxx.com": "Adult advertising",
    "eroadvertising.com": "Adult advertising",
    "adxxx.org": "Adult advertising",
    "ibillboard.com": "Web advertising platform",
    "tubemogul.com": "A company with multiple advertising roles",
    "planet-traffic.com": "Traffic generator",
    "safelistsubmitters.com": "Traffic generator",
    "bannersnack.net": "Traffic generator",
    "safe-list.com": "Traffic generator",
    "licasd.com": "Unknown Service",
    "bluekai.com": "Web advertising platform",
    "verizon.com": "A company with multiple advertising roles",
    "lotame.com": "User tracking service",
    "nocookie.net": "Image hosting service",
    "googleadservices.com": "A company with multiple advertising roles",
    "ru4.com": "User tracking service",
    "sphere.com": "User tracking service",
    "appspot.com": "Cloud services",
    "twimg.com": "Social network",
    "instagram.com": "Social network",
    "tumblr.com": "Social network",
    "linkedin.com": "Social network",
    "myspace.com": "Social network",
    "vk.com": "Social network",
    "twitter.com": "Social network",
    "cdninstagram.com": "Social network",
    "twitch.tv": "Social network",
    "skype.com": "Social network",
    "atlassbx.com": "Social network",
    "scdn.co": "Social network",
    "spotify.com": "Social network",
    "facebook.com": "Social network",
    "facebook.net": "Social network",
    "fbsbx.com": "Social network",
    "fbcdn.net": "Social network",
    "licdn.com": "Social network",
    "flickr.com": "Social network",
    "atdmt.com": "Social network",
    "wikia.com": "Social network",
    "negnog.pl": "User tracking service",
    "adnext.fr": "Web advertising platform",
    "yandex.com": "A company with multiple advertising roles",
    "adsafeprotected.com": "Bot and web scraping protection for advertising",
    "areyouahuman.com": "Bot and web scraping protection for advertising",
    "grvcdn.com": "A company with multiple advertising roles",
    "everestads.net": "A company with multiple advertising roles",
    "xblasterads.com": "Web advertising platform",
    "czilladx.com": "Crypto advertising",
    "tiqcdn.com": "Marketing data management platform",
    "basebanner.com": "Web advertising platform",
    "iasds01.com": "Marketing data management platform",
    "yandex.st": "A company with multiple advertising roles",
    "yandex.ru": "A company with multiple advertising roles",
    "ligadx.com": "Web advertising platform",
    "amazon-adsystem.com": "A company with multiple advertising roles",
    "gstatic.com": "A company with multiple advertising roles",
    "google.co.ve": "A company with multiple advertising roles",
    "google.ru": "A company with multiple advertising roles",
    "google.com.pe": "A company with multiple advertising roles",
    "google.co.id": "A company with multiple advertising roles",
    "google.com.tr": "A company with multiple advertising roles",
    "office.com": "Cloud services",
    "office365.com": "Cloud services",
    "openx.com": "Web advertising platform",
    "openx.net": "Web advertising platform",
    "xblasterads1.com": "Web advertising platform",
    "outbrainimg.com": "Web advertising platform",
    "google-analytics.com": "User tracking service",
    "acxiom.com": "Web advertising platform",
    "tripadvisor.fr": "Traveling services",
    "tripadvisor.it": "Traveling services",
    "tripadvisor.com": "Traveling services",
    "tripadvisor.co.uk": "Traveling services",
    "travelsmarter.net": "Traveling services",
    "smartertravel.com": "Traveling services",
    "bstatic.com": "Traveling services",
    "booking.com": "Traveling services",
    "tamgrt.com": "Traveling services",
    "google.ro": "A company with multiple advertising roles",
    "google.com.do": "A company with multiple advertising roles",
    "google.cl": "A company with multiple advertising roles",
    "google.com.vn": "A company with multiple advertising roles",
    "google.co.za": "A company with multiple advertising roles",
    "google.gr" : "A company with multiple advertising roles",
    "google.md" : "A company with multiple advertising roles",
    "google.fi": "A company with multiple advertising roles",
    "google.com.mx": "A company with multiple advertising roles",
    "google.com.eg": "A company with multiple advertising roles",
    "google.tn": "A company with multiple advertising roles",
    "google.ca": "A company with multiple advertising roles",
    "googleusercontent.com": "A company with multiple advertising roles",
    "google.com.cy": "A company with multiple advertising roles",
    "googletagmanager.com": "A company with multiple advertising roles",
    "google.com.br": "A company with multiple advertising roles",
    "google.bg": "A company with multiple advertising roles",
    "google.rs": "A company with multiple advertising roles",
    "google.com.sa": "A company with multiple advertising roles",
    "google.es": "A company with multiple advertising roles",
    "google.com.ar": "A company with multiple advertising roles",
    "googleapis.com": "A company with multiple advertising roles",
    "googlesyndication.com": "A company with multiple advertising roles",
    "google.dk": "A company with multiple advertising roles",
    "google.de": "A company with multiple advertising roles",
    "google.co.uk": "A company with multiple advertising roles",
    "google.co.in": "A company with multiple advertising roles",
    "analytics-google.net": "A company with multiple advertising roles",
    "google.nl": "A company with multiple advertising roles",
    "google.mk": "A company with multiple advertising roles",
    "google.it": "A company with multiple advertising roles",
    "google.com": "A company with multiple advertising roles",
    "google.com.np": "A company with multiple advertising roles",
    "google.ae": "A company with multiple advertising roles",
    "google.co.nz": "A company with multiple advertising roles",
    "google.ba": "A company with multiple advertising roles",
    "google.lk": "A company with multiple advertising roles",
    "doubleclick.net": "A company with multiple advertising roles",
    "google.com.co": "A company with multiple advertising roles",
    "google.com.ua": "A company with multiple advertising roles",
    "google.be": "A company with multiple advertising roles",
    "ssl-images-amazon.com": "A company with multiple advertising roles",
    "images-amazon.com": "A company with multiple advertising roles",
    "amazon.es": "A company with multiple advertising roles",
    "amazon.co.uk": "A company with multiple advertising roles",
    "amazon.de": "A company with multiple advertising roles",
    "amazon.com": "A company with multiple advertising roles",
    "amazon.it": "A company with multiple advertising roles",
    "assoc-amazon.com": "A company with multiple advertising roles",
    "gvt1.com": "A company with multiple advertising roles",
    "youtube.com": "Video service",
    "adobe.com": "A company with multiple advertising roles",
    "demdex.net": "A company with multiple advertising roles",
    "amazonaws.com": "Cloud services",
    "wordpress.com": "Web hosting service",
    "ebay.in": "e-commerce services",
    "ebay.co.uk": "e-commerce services",
    "ebay.es": "e-commerce services",
    "ebay.com": "e-commerce services",
    "ebayimg.com": "e-commerce services",
    "ebaystatic.com": "e-commerce services",
    "ebay.de": "e-commerce services",
    "ebaystatic.com": "e-commerce services",
    "alibaba.com": "e-commerce services",
    "aliexpress.com": "e-commerce services",
    "shopbop.com": "e-commerce services",
    "alicdn.com": "Cloud services",
    "vimeo.com": "Video service",
    "vimeocdn.com": "Video service",
    "livestream.com": "Video service",
    "yandex.net": "Web advertising platform",
    "yandexadexchange.net": "Web advertising platform",
    "hsforms.net": "Customer Relationship Management - CRM Platform",
    "waze.com": "Ride sharing service",
    "casalemedia.com": "Web advertising platform",
    "disquscdn.com": "Live chat service",
    "disqus.com": "Live chat service",
    "zendesk.com": "Live chat service",
    "disqusads.com": "Web advertising platform",
    "pippio.com": "Web advertising platform",
    "omnitagjs.com": "User tracking service",
    "rlcdn.com": "User tracking service",
    "bannersnack.com": "Web advertising platform",
    "gfx.ms": "A company with multiple advertising roles",
    "tidaltv.com": "Video advertising platform",
    "mmstat.com": "User tracking service",
    "adap.tv": "A company with multiple advertising roles",
    "s-microsoft.com": "A company with multiple advertising roles",
    "mediaforge.com": "Web advertising platform",
    "data-slimspots.com": "Web advertising platform",
    "slimspots.com": "Web advertising platform",
    "adk2x.com": "Web advertising platform",
    "sharepoint.com": "A company with multiple advertising roles",
    "techcrunch.com": "A company with multiple advertising roles",
    "microsoftonline-p.com": "A company with multiple advertising roles",
    "ggpht.com": "A company with multiple advertising roles",
    "fwmrm.net": "User tracking service",
    "seadform.net": "Web advertising platform",
    "weborama.io": "Web advertising platform",
    "247realmedia.com": "Web advertising platform",
    "stripe.network": "User tracking service",
    "coinzilla.io": "Crypto advertising",
    "easyhits4u.net": "Traffic generator",
    "easyhits4u.us": "Traffic generator",
    "easyhits4u.com": "Traffic generator",
    "easysplashbuilder.net": "Traffic generator",
    "easysplashbuilder.com": "Traffic generator",
    "easyrotator.net": "Traffic generator",
    "bkrtx.com": "Traffic generator",
    "os.tc": "Web advertising platform",
    "isu.pub": "Web advertising platform",
    "xplosion.de": "Web advertising platform",
    "mookie1.com": "Web advertising platform",
    "jwpltx.com": "Web advertising platform",
    "clmbtech.com": "User tracking service",
    "avid-ad-server.com": "Web advertising platform",
    "outbrain.com": "Web advertising platform",
    "advertica-cdn2.com": "Web advertising platform",
    "criteo.com": "Web advertising platform",
    "criteo.net": "Web advertising platform",
    "specificclick.net": "Web advertising platform",
    "intellitxt.com": "Web advertising platform",
    "adbrn.com": "User tracking service",
    "veedi.com": "Gaming videos",
    "veedif.com": "Gaming videos",
    "switchadhub.com": "Live concepts services",
    "addthis.com": "User tracking service",
    "clickfunnels.com": "smart affiliate marketing solutions",
    "clickfunnel.com": "smart affiliate marketing solutions",
    "ultimedia.com": "smart affiliate marketing solutions",
    "audible.com": "A company with multiple advertising roles",
    "indexww.com": "User tracking service",
    "liadm.com": "User tracking service",
    "tacdn.com": "A company with multiple advertising roles",
    "betrad.com": "Web advertising platform",
    "mail.ru": "User tracking service",
    "exelator.com": "User tracking service",
    "marketo.com": "A company with multiple advertising roles",
    "marketo.net": "A company with multiple advertising roles",
    "microsoft.com": "A company with multiple advertising roles",
    "ampproject.org": "A company with multiple advertising roles",
    "ampproject.net": "A company with multiple advertising roles",
    "ad4mat.net": "Web advertising platform",
    "trustarc.com": "User concent",
    "truste-svc.net": "User concent",
    "truste.com": "User concent",
    "cloudfront.net": "A company with multiple advertising roles",
    "adsensecustomsearchads.com": "A company with multiple advertising roles",
    "typekit.net": "A company with multiple advertising roles",
    "atlassian.com": "Cloud services",
    "atlassian.net": "Cloud services",
    "adsk2.co": "Web advertising platform",
    "dtmpub.com": "User tracking service",
    "engadget.com": "Technology reviews",
    "dpreview.com": "Technology reviews",
    "adspdbl.com": "Web advertising platform",
    "lockerdomecdn.com": "Web advertising platform",
    "lockerdome.com": "Web advertising platform",
    "boxofficemojo.com": "Movie reviews",
    "imdb.com": "Movie reviews",
    "digiteka.net": "Video advertising platform",
    "distiltag.com": "Bot and web sraping protection for advertising",
    "perfectmarket.com": "Web advertising platform",
    "twyn.com": "Marketing data management platform",
    "twyn-group.com": "Marketing data management platform",
    "effectivemeasure.com": "Marketing data management platform",
    "brightcove.com": "Video advertising platform",
    "brightcove.net": "Video advertising platform",
    "appnexus.com": "Web advertising platform",
    "yammer.com": "A company with multiple advertising roles",
    "cedexis.com": "Web advertising platform",
    "ytimg.com": "A company with multiple advertising roles",
    "yastatic.net": "A company with multiple advertising roles",
    "gravity.com": "User tracking service",
    "cnn.com": "News aggregation service",
    "indiatimes.com": "News aggregation service",
    "convertro.com": "A company with multiple advertising roles",
    "web.de": "Email services",
    "ucoz.net": "Website builder",
    "ucoz.ru": "Website builder",
    "wp.com": "Website builder",
    "rfihub.net": "Web advertising platform",
    "adnxs.net": "Web advertising platform",
    "turn.com": "Web advertising platform",
    "gmail.com": "Email services",
    "weborama.fr": "Web advertising platform",
    "mercadopago.com": "Financial services",
    "wistia.net": "Multimedia Services",
    "embed.ly": "Multimedia Services",
    "gravatar.com": "User tracking service",
    "zdassets.com": "User tracking service",
    "vibrantmedia.com": "Web advertising platform",
    "leadpages.net": "Marketing data management platform",
    "center.io": "Marketing data management platform",
    "microsoftonline.com": "A company with multiple advertising roles",
    "aliyun.com": "Cloud services",
    "livedap.com": "Web advertising platform",
    "addthisedge.com": "Web advertising platform",
    "samsung.com": "Technology company",
    "mediamath.com": "Web advertising platform",
    "ad6media.fr": "Web advertising platform",
    "ad6.fr": "Web advertising platform",
    "ib-ibi.com": "User tracking service",
    "serving-sys.com": "A company with multiple advertising roles",
    "mediaplex.com": "User tracking service",
    "ylx-1.com": "Web advertising platform",
    "ylx-2.com": "Web advertising platform",
    "adtech.de": "Web advertising platform",
    "metadsp.co.uk": "Web advertising platform",
    "mathtag.com": "User tracking service",
    "servedbyadbutler.com": "User tracking service",
    "adbutler-fermion.com": "User tracking service",
    "polldaddy.com": "User tracking service",
    "tableau.com": "Marketing data management platform",
    "tableausoftware.com": "Marketing data management platform",
    "tfd.com": "User tracking service",
    "crwdcntrl.net": "Web advertising platform",
    "hlserve.com": "User tracking service",
    "mktoresp.com": "A company with multiple advertising roles",
    "bing.com": "A company with multiple advertising roles",
    "bbelements.com": "Web advertising platform",
    "adfox.ru": "Web advertising platform",
    "weborama.com": "Web advertising platform",
    "onesignal.com": "Web advertising platform",
    "thetradedesk.com": "Web advertising platform",
    "ligatus.com": "Web advertising platform",
    "dmtry.com": "A company with multiple advertising roles",
    "dpclk.com": "User tracking service",
    "w55c.net": "User tracking service",
    "adsrvr.org": "Web advertising platform",
    "tagdelivery.com": "Web advertising platform",
    "brand-server.com": "Web advertising platform",
    "amgdgt.com": "Web advertising platform",
    "theplatform.com": "Video advertising platform",
    "avidadserver.com": "Web advertising platform",
    "adverline.com": "Web advertising platform",
    "effectivemeasure.net": "Web advertising platform",
    "tealiumiq.com": "User tracking service",
    "2mdn.net": "User tracking service",
    "emetriq.de": "User tracking service",
    "issuu.com": "Web advertising platform",
    "nurno.com": "Web advertising platform",
    "dataxu.net": "Marketing data management platform",
    "uimserv.net": "Marketing data management platform",
    "omnitagsb.com": "Marketing data management platform",
    "vidible.tv": "Video advertising platform",
    "farlex.com": "User tracking service",
    "img-bahn.de": "public transport services",
    "zanox.ws": "Web advertising platform",
    "rfihub.com": "Web advertising platform",
    "ad4mat.de": "Web advertising platform",
    "mapquest.com": "User tracking service",
    "emxdgt.com": "User tracking service",
    "wistia.com": "Video advertising platform",
    "brealtime.com": "Web advertising platform",
    "everesttech.net": "A company with multiple advertising roles",
}

